// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run against the direct (non-pooled) connection - Supabase's
    // pooler (used for DATABASE_URL at runtime, see src/lib/prisma.ts) doesn't
    // reliably support the DDL/session features `migrate` needs.
    url: process.env["DIRECT_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
